// Copyright 2023 Vic Shóstak and Create Go App Contributors. All rights reserved.
// Use of this source code is governed by Apache 2.0 license
// that can be found in the LICENSE file.

package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/create-go-app/cli/v4/pkg/cgapp"
	"github.com/create-go-app/cli/v4/pkg/contract"
	"github.com/create-go-app/cli/v4/pkg/registry"
)

func init() {
	rootCmd.AddCommand(deployCmd)
	deployCmd.Flags().BoolVarP(
		&askBecomePass,
		"ask-become-pass", "k", false,
		"prompt you to provide the remote user sudo password (standard Ansible `--ask-become-pass` option)",
	)
}

// deployCmd represents the `deploy` command.
var deployCmd = &cobra.Command{
	Use:     "deploy",
	Aliases: []string{"push"},
	Short:   "Deploy your project to the remote server via Ansible",
	Long:    "\nDeploy your project to the remote server by Ansible playbooks and roles.",
	RunE:    runDeployCmd,
}

// runDeployCmd represents runner for the `deploy` command.
func runDeployCmd(cmd *cobra.Command, args []string) error {
	// Start message.
	cgapp.ShowMessage(
		"",
		fmt.Sprintf("Deploying project via Create Go App CLI v%v...", registry.CLIVersion),
		true, true,
	)

	// Verify local prerequisites and generated artifacts before connecting.
	if err := deployPreflight(); err != nil {
		return cgapp.ShowError(err.Error())
	}

	// Set Ansible playbook and inventory files.
	if askBecomePass {
		// With entering password.
		options = []string{"playbook.yml", "-i", "hosts.ini", "-K"}
	} else {
		// Without entering password.
		options = []string{"playbook.yml", "-i", "hosts.ini"}
	}

	// Create config files for your project.
	cgapp.ShowMessage(
		"info",
		"Ansible playbook for deploy your project is running. Please wait for completion!",
		false, false,
	)

	// Start timer.
	startTimer := time.Now()

	// Run execution for Ansible playbook.
	if err := cgapp.ExecCommand("ansible-playbook", options, false); err != nil {
		return cgapp.ShowError(err.Error())
	}

	// Stop timer.
	stopTimer := cgapp.CalculateDurationTime(startTimer)
	cgapp.ShowMessage(
		"info",
		fmt.Sprintf("Completed in %v seconds!", stopTimer),
		false, true,
	)

	// Ending message.
	cgapp.ShowMessage(
		"",
		"Have a great project launch! :)",
		false, true,
	)

	return nil
}

// deployPreflight checks that Ansible is installed and that the current
// directory contains a project generated by a compatible CLI version.
func deployPreflight() error {
	if _, err := exec.LookPath("ansible-playbook"); err != nil {
		return fmt.Errorf(
			"ansible-playbook was not found in PATH; install Ansible first " +
				"(see https://docs.ansible.com/ansible/latest/installation_guide/)",
		)
	}

	for _, file := range []string{"playbook.yml", "hosts.ini"} {
		if _, err := os.Stat(file); err != nil {
			return fmt.Errorf("%q not found; run `cgapp create` in this directory first", file)
		}
	}
	if _, err := os.Stat("roles"); err != nil {
		return fmt.Errorf("roles directory not found; run `cgapp create` in this directory first")
	}

	inventory, err := os.ReadFile("hosts.ini")
	if err != nil {
		return fmt.Errorf("can't read hosts.ini: %w", err)
	}
	if !strings.Contains(string(inventory), "cgapp_contract="+contract.SchemaVersion) {
		return fmt.Errorf(
			"hosts.ini was not generated by this CLI version (missing contract marker %q); "+
				"regenerate the project or deploy with the matching CLI",
			contract.SchemaVersion,
		)
	}

	// The default inventory ships a placeholder IP; refuse to deploy until
	// the user changes it.
	if strings.Contains(string(inventory), "127.0.0.1 # CHANGE THIS TO YOUR REMOTE SERVER IP!") {
		return fmt.Errorf(
			"set the remote server IP in hosts.ini (the 127.0.0.1 placeholder is still present)",
		)
	}

	return nil
}
